name: Build and Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
      - 'draft-*'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > lingxis-keystore.jks

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}

      - name: Rename APK and Generate SHA256
        run: |
          VERSION=${{ github.ref_name }}
          # Sanitize the version string to be a valid filename component
          VERSION=$(echo "$VERSION" | sed 's/[\/]/_/g')
          DATE=$(date +%Y%m%d)
          NEW_NAME="lingxis2048_universal_${VERSION}_${DATE}.apk"
          mv app/build/outputs/apk/release/app-release.apk "app/build/outputs/apk/release/${NEW_NAME}"
          cd app/build/outputs/apk/release
          sha256sum "${NEW_NAME}" > "${NEW_NAME}.sha256sum"
          cd -

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-artifacts
          path: |
            app/build/outputs/apk/release/lingxis2048_*.apk
            app/build/outputs/apk/release/lingxis2048_*.apk.sha256sum

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lingxis2048_*.apk,lingxis2048_*.apk.sha256sum"
          bodyFile: "releaseNotes/Release${{ replace(github.ref_name, 'v', '') }}.md"
          token: ${{ secrets.GITHUB_TOKEN }}